id: A0A0CA3B4
title: f68DD
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:34:03.058978
  last_modified_at: 2022-05-27 15:34:03.058981
