id: A0A0CA3B4
title: f57A6
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:34:03.049734
  last_modified_at: 2022-05-27 15:34:03.049739
